# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 09:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('money', models.PositiveIntegerField(default=2000)),
                ('partner', models.BooleanField(default=False)),
                ('happiness', models.PositiveIntegerField(default=50)),
                ('tiredness', models.PositiveIntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentsSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('complexity', models.FloatField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('complexity', models.FloatField()),
                ('connected_skills', models.ManyToManyField(to='game.Skill')),
                ('connected_subject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='game.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.ManyToManyField(through='game.StudentsSkill', to='game.Skill'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skill',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Student'),
        ),
    ]
