# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-08 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='title',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='stage',
            name='code_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
