# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-08 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20170208_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
