# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-09 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20170208_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
