# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-09 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_stagetype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StageType',
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='choice',
            name='title',
            field=models.CharField(default='', max_length=30),
        ),
    ]
