# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-10 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20170209_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stage',
            old_name='code_name',
            new_name='codename',
        ),
    ]
