# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extuser',
            name='username',
            field=models.TextField(max_length=20, unique=True, verbose_name='Имя Пользователя'),
        ),
    ]
