# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extuser', '0002_auto_20161005_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=30, unique=True, verbose_name='Электронная почта'),
        ),
    ]
