# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extuser', '0003_auto_20161005_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='extuser',
            name='visits_count',
            field=models.IntegerField(default=0, verbose_name='Кол-во посещений сайта'),
        ),
    ]
