# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extuser', '0005_remove_extuser_visits_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extuser',
            name='username',
            field=models.CharField(max_length=20, unique=True, verbose_name='Имя Пользователя'),
        ),
    ]
