# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 03:18
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2016, 10, 9, 3, 18, 22, 463073, tzinfo=utc))),
                ('visits_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserDayVisits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visits_count', models.IntegerField(default=0)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.Day')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='visiters',
            field=models.ManyToManyField(through='visits.UserDayVisits', to=settings.AUTH_USER_MODEL),
        ),
    ]
