# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_auto_20161009_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, unique=True),
        ),
        migrations.AlterField(
            model_name='userdayvisits',
            name='visits_count',
            field=models.IntegerField(default=1),
        ),
    ]
