# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_auto_20161009_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdayvisits',
            name='visits_count',
            field=models.IntegerField(default=0),
        ),
    ]
