# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0004_auto_20161009_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='anonimous_visits_count',
            field=models.IntegerField(default=0),
        ),
    ]
