# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0005_day_anonimous_visits_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField()),
                ('browser', models.TextField()),
                ('os', models.TextField()),
                ('cookies', models.TextField()),
                ('last_hit', models.DateTimeField(default=django.utils.timezone.now)),
                ('hit_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='day',
            name='visiters',
        ),
        migrations.RemoveField(
            model_name='userdayvisits',
            name='day',
        ),
        migrations.RemoveField(
            model_name='userdayvisits',
            name='user',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='UserDayVisits',
        ),
    ]
