# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0006_auto_20161009_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='os',
        ),
        migrations.AlterField(
            model_name='visit',
            name='hit_count',
            field=models.IntegerField(default=1),
        ),
    ]
