# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0007_auto_20161009_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='os',
            field=models.TextField(default=''),
        ),
    ]
