# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0011_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='visit',
        ),
        migrations.AddField(
            model_name='visit',
            name='url',
            field=models.ManyToManyField(to='visits.Url'),
        ),
    ]
