# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0012_auto_20161123_1654'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Url',
            new_name='Urls',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='url',
            new_name='urls',
        ),
    ]
