# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0014_auto_20161123_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.Visit')),
            ],
        ),
    ]
