# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-24 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0016_visit_urls_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='urls_text',
            field=models.TextField(default='start'),
        ),
    ]
