# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-24 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0017_auto_20161124_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urls',
            name='visit',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='urls_text',
        ),
        migrations.AddField(
            model_name='visit',
            name='urls',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Urls',
        ),
    ]
