# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-24 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0018_auto_20161124_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='urls',
            field=models.TextField(blank=True),
        ),
    ]
