# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0019_auto_20161124_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie', models.TextField()),
                ('ip', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='browser',
            new_name='user_agent',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='ip',
        ),
    ]
