# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0020_auto_20170109_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='urls',
        ),
        migrations.AddField(
            model_name='visiter',
            name='urls',
            field=models.TextField(blank=True),
        ),
    ]
