# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0021_auto_20170110_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='screen',
            field=models.TextField(default='JS был выключен'),
        ),
    ]
