# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0023_auto_20170110_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='visiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='visits.Visiter'),
        ),
    ]
