# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-13 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0029_auto_20170113_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='last_hit',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
