# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0032_visit_visiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.Visiter'),
        ),
    ]
